import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Readable } from "node:stream";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import { parseUrlManifest, readUrlManifest } from "../cli/url-manifest.js";

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

describe("parseUrlManifest", () => {
  it("ignores blank lines and full-line comments", () => {
    const result = parseUrlManifest(
      "# generated paths\n\n/\n  # another comment\n",
      "https://example.com",
      "urls.txt",
    );

    expect(result).toEqual({ paths: ["/"], issues: [] });
  });

  it("rejects a manifest with no effective paths", () => {
    const result = parseUrlManifest(
      "\n # generated by a crawler\r\n",
      "https://example.com",
      "urls.txt",
    );

    expect(result).toEqual({
      paths: [],
      issues: [
        {
          type: "manifest",
          source: "urls.txt",
          message: "URL manifest must contain at least one path",
        },
      ],
    });
  });

  it("reports every invalid entry with its source line", () => {
    const result = parseUrlManifest(
      "/\nabout-me\n//other.example/about\nhttps://example.com/about\n/bad%escape\n",
      "https://example.com",
      "urls.txt",
    );

    expect(result).toEqual({
      paths: ["/"],
      issues: [
        {
          type: "entry",
          source: "urls.txt",
          line: 2,
          value: "about-me",
          message: "Path must be root-relative and begin with exactly one '/'",
        },
        {
          type: "entry",
          source: "urls.txt",
          line: 3,
          value: "//other.example/about",
          message: "Cross-origin or scheme-relative paths are not allowed",
        },
        {
          type: "entry",
          source: "urls.txt",
          line: 4,
          value: "https://example.com/about",
          message: "Path must be root-relative and begin with exactly one '/'",
        },
        {
          type: "entry",
          source: "urls.txt",
          line: 5,
          value: "/bad%escape",
          message: "Path contains an invalid percent escape",
        },
      ],
    });
  });

  it("deduplicates canonical paths in first-seen order", () => {
    const result = parseUrlManifest(
      "/about\n/about/../about\n/blog?draft=1\n/blog?draft=1\n/\n",
      "https://example.com",
      "urls.txt",
    );

    expect(result).toEqual({
      paths: ["/about", "/blog?draft=1", "/"],
      issues: [],
    });
  });

  it("preserves fragments and treats only full lines as comments", () => {
    const result = parseUrlManifest(
      "/page#section\n/page#section\n/page#other\npage#relative\n",
      "https://example.com",
      "urls.txt",
    );

    expect(result).toEqual({
      paths: ["/page#section", "/page#other"],
      issues: [
        {
          type: "entry",
          source: "urls.txt",
          line: 4,
          value: "page#relative",
          message: "Path must be root-relative and begin with exactly one '/'",
        },
      ],
    });
  });

  it("rejects a base URL that is not HTTP(S)", () => {
    const result = parseUrlManifest(
      "/\n/about\n",
      "ftp://example.com",
      "urls.txt",
    );

    expect(result).toEqual({
      paths: [],
      issues: [
        {
          type: "manifest",
          source: "urls.txt",
          message: "Base URL must be a valid HTTP(S) URL: ftp://example.com",
        },
      ],
    });
  });

  it("reads a manifest from an explicit stdin stream", async () => {
    const input = Readable.from(["# generated\n", "/\n", "/about\n"]);

    await expect(readUrlManifest("-", input)).resolves.toBe(
      "# generated\n/\n/about\n",
    );
  });

  it("reports a contextual error when stdin cannot be read", async () => {
    const input = Readable.from(
      (async function* () {
        throw new Error("broken pipe");
      })(),
    );

    await expect(readUrlManifest("-", input)).rejects.toThrow(
      "Unable to read URL manifest from stdin: broken pipe",
    );
  });

  it("reads a manifest file relative to the caller", async () => {
    const directory = await mkdtemp(join(tmpdir(), "breakcheck-manifest-"));
    temporaryDirectories.push(directory);
    const source = join(directory, "urls.txt");
    await writeFile(source, "/\n/about\n", "utf8");

    await expect(readUrlManifest(source)).resolves.toBe("/\n/about\n");
  });

  it("reports a contextual error when the manifest file cannot be read", async () => {
    const directory = await mkdtemp(join(tmpdir(), "breakcheck-manifest-"));
    temporaryDirectories.push(directory);
    const source = join(directory, "missing.txt");

    await expect(readUrlManifest(source)).rejects.toThrow(
      `Unable to read URL manifest from ${source}`,
    );
  });
});
